### PR TITLE
Truly cross platform : Nov 1st deadline

### PR DESCRIPTION
**Pull request by gagbo**
Trying to follow the calendar here. Here's a more fleshed out version for the article.

All quotes are actually comments. @romainl I've put a small question for you in the middle : why still using the call to `uname` in setEnv() while vim has `osx` and `osx_darwin` features ? Are there cases where uname returns darwin but both `has(osx)` and `has(osx_darwin)` are false ?

### CODE REVIEW

**Comment by romainl** [comment]
That snippet has been in my config in one form or another for a long time and, well… I actually didn't even know about `osx`.

Anyway, MacVim does honor both `macunix` and `osx` but `/usr/bin/vim` doesn't, so `uname` is basically the only safe way to determine that you are on a Mac. I don't have Mojave so this may have changed in the mean time.

**Comment by romainl** [comment]
About autoloading: since it doesn't change anything to the example at hand, mentioning it at that point would add unneeded complexity. FWIW, if that function is in a larger file with many functions, Vim will source the whole file, potentially slowing startup.

**Comment by romainl** [comment]
About host-specific stuff: it's pretty spot-on IMO but it would be better with a working example. Windows has [a `hostname`command](https://ss64.com/nt/hostname.html), too, so this shouldn't be too difficult.

Also, you are mentioning "cluster", which is not exactly a common thing. Could you give your reader a bit of background? "I use Windows at work and Linux at home" is common but "I work on clusters" is fancy and sounds exciting.

**Comment by gagbo** [comment]
I agree on most of this stuff, so I made a few corrections : 
- I basically linked the comment on `macunix` and `osx` here, stating that it may not work as you'd want it to.
- Removed autoloading in functions
- Explained what I do, and how the need for 'Host specific settings' arised in my work. I used the occasion to present one way to hide hostnames (or possibly other information) from your version controlled files if they happen to be public.

**Pull request merged**
